---
json:
  - rigid
  - better for data interchange
yaml:
  - slim and flexible
  - better for configuration
object:
  key: value
  array:
    - null_value:
    - boolean: true
    - integer: 1
paragraph: Blank lines denote paragraph breaks
content:
   Or we
   can auto
   convert line breaks
   to save space